version: '3'
services:
  memcached:
    image: 'memcached:latest'
  nginx:
    image: 'nginx:latest'
    ports:
      - 8080:80
      - 4444:443
    volumes:
      - './wordpress:/var/www/html'
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - phpfpm
    environment:
      CERT_NAME: localhost
      HTTPS_METHOD: noredirect
  phpfpm:
    build: .
    volumes:
      - './wordpress:/var/www/html'
      - './config/php-fpm/php.ini:/usr/local/etc/php/php.ini'
      - './config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
      - 'wplocaldockerCache:/var/www/.wp-cli/cache'
      - './config/php-fpm/wp-cli.local.yml:/var/www/.wp-cli/config.yml'
      - './backup:/tmp/backup'
    depends_on:
      - mysql
      - memcached
  mysql:
    image: mysql:5
    command: --sql_mode=""
    volumes:
      - "mysqlData:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  mysqlData: {}
  wplocaldockerCache: {}
  elasticsearchData: {}
