version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: circleci/mariadb:10.3.4-ram
        environment:
          MARIADB_USER: root
          MARIADB_DB: wordpress

    working_directory: ~/dev-ctoec

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: Wait for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      - run: 
          name: Update dependencies
          command: |
            sudo apt-get update -q
            sudo apt install -y mysql-client
            sudo apt-get install -y lftp

      - run: echo 127.0.0.1 dev-ctoec.dev | sudo tee -a /etc/hosts

      - run: 
          name: Install WP-CLI
          command: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      
      - run:
          name: Creating database
          command: mysql  -h 127.0.0.1 -u root -e "create database wordpress;"

      - run: 
          name: Setting WP-CLI permissions
          command: chmod +x wp-cli.phar

      - run:
          name: Downloading WP core
          command: ./wp-cli.phar core download --path=wordpress

      - run:
          name: Creating WP config file
          command: ./wp-cli.phar config create --allow-root --dbname=wordpress --dbuser=root --dbhost=127.0.0.1 --path=wordpress
      
      - run: 
          name: Updating composer
          command: sudo composer self-update

      - run:
          name: Installing WP themes and plugins via Composer
          command: composer install -n --prefer-dist

      - run:
          name: Deploy theme
          command: sftp://${SFTP_USERNAME}:${SFTP_PASSWORD}@${SFTP_HOSTNAME} -e 'mirror -v -R ./${THEME_NAME} ./wp-content/themes/${THEME_NAME}; quit'