workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: prod

version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3
      - image: circleci/mariadb:10.3.4-ram
        environment:
          MARIADB_USER: root
          MARIADB_DB: wordpress

    working_directory: ~/dev-ctoec

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run:
          name: Update dependencies
          command: |
            sudo apt-get update -q
            sudo apt install -y mysql-client

      - run:
          name: Creating database
          command: |

            function dbIsDown { mysqladmin -h 127.0.0.1 -u root status  > /dev/null 2>&1 && echo "$?"; }

            while [ -z $(dbIsDown)  ]; do
                echo "waiting for mysql to start working"
                sleep 3s
            done

            mysql -h 127.0.0.1 -u root -e "create database wordpress;"

      - run: 
          name: Install WP-CLI and WP Core
          command: | 
            set -x
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            ./wp-cli.phar core download --path=wordpress

      - run:
          name: Creating WP config file
          command: ./wp-cli.phar config create --allow-root --dbname=wordpress --dbuser=root --dbhost=127.0.0.1 --path=wordpress
      
      - run:
          name: Installing WP themes and plugins via Composer
          command: sudo composer self-update && composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - wordpress

  publish-prod:
    docker:
      - image: circleci/php:7.3
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Update dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y lftp
      - run:
          name: Publish to Prod
          command: |
            lftp sftp://${SFTP_USERNAME}:${SFTP_PASSWORD}@${SFTP_HOSTNAME} -e "set ssl: verify-certificate no; set sftp:auto-confirm yes; mirror --exclude _dev/ -v -R ./wordpress/wp-content/themes/${THEME_NAME} ${SITE_PATH}/wp-content/themes/${THEME_NAME}; quit"
          