version: 2

orbs:
  percy: percy/agent@0.1.2

jobs:

  build:
    docker:
      - image: circleci/php:7.3
      - image: circleci/mariadb:10.3.4-ram
        environment:
          MARIADB_USER: root
          MARIADB_DB: wordpress

    steps:
      - checkout

      - run:
          name: Update dependencies
          command: |
            sudo apt-get update -q
            sudo apt install -y mysql-client

      - run:
          name: Create database
          command: |
            function dbIsDown { mysqladmin -h 127.0.0.1 -u root status  > /dev/null 2>&1 && echo "$?"; }

            while [ -z $(dbIsDown)  ]; do
                echo "waiting for mysql to start working"
                sleep 3s
            done

            mysql -h 127.0.0.1 -u root -e "create database wordpress;"

      - run:
          name: Install WP-CLI and WP Core
          command: |
            set -x
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            ./wp-cli.phar core download --path=wordpress

      - run:
          name: Download theme
          command: |
            if [[ $CIRCLE_BRANCH = "master" ]]; then DEPLOY_BRANCH=master; else DEPLOY_BRANCH=dev; fi
            git clone -b ${DEPLOY_BRANCH} --single-branch https://github.com/ctoec/benjamin.git wordpress/wp-content/themes/ctoec
            rm -rf wordpress/wp-content/themes/ctoec/.git

      - run:
          name: Creating WP config file
          command: ./wp-cli.phar config create --allow-root --dbname=wordpress --dbuser=root --dbhost=127.0.0.1 --path=wordpress

      - run:
          name: Installing WP themes and plugins via Composer
          command: sudo composer self-update && composer install -n --prefer-dist

      - persist_to_workspace:
          root: .
          paths:
            - wordpress/wp-content/themes/${THEME_NAME}/*

  deploy-staging:
    docker:
      - image: circleci/php:7.3
    steps:
      - attach_workspace:
          at: wordpress
      - run:
          name: Update dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y lftp

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
